from __future__ import annotations

from copy import deepcopy
from pathlib import Path
import re
from typing import Any

from model import Chapter, Project, Quest, Reward, Task


_SAFE_KEY = re.compile(r"^[A-Za-z0-9_+\-./]+$")


def _escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def _format_key(key: str) -> str:
    return key if _SAFE_KEY.fullmatch(key) else f'"{_escape(key)}"'


def dumps(value: Any, *, indent: int = 0) -> str:
    """Serialize ordinary Python values to readable SNBT.

    FTB Quests accepts standard compounds/lists and numeric suffixes. Booleans are
    emitted as bytes because that is the format generated by FTB Quests itself.
    """
    level = "\t" * indent
    child = "\t" * (indent + 1)

    if isinstance(value, bool):
        return "1b" if value else "0b"
    if value is None:
        return '""'
    if isinstance(value, str):
        return f'"{_escape(value)}"'
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return f"{value:.15g}d"
    if isinstance(value, dict):
        if not value:
            return "{ }"
        lines = ["{"]
        for key, item in value.items():
            rendered = dumps(item, indent=indent + 1)
            lines.append(f"{child}{_format_key(str(key))}: {rendered}")
        lines.append(f"{level}}}")
        return "\n".join(lines)
    if isinstance(value, (list, tuple)):
        if not value:
            return "[ ]"
        # Compact primitive lists; expand nested structures for readable diffs.
        if all(not isinstance(item, (dict, list, tuple)) for item in value):
            return "[ " + ", ".join(dumps(item, indent=indent + 1) for item in value) + " ]"
        lines = ["["]
        for item in value:
            rendered = dumps(item, indent=indent + 1)
            lines.append(f"{child}{rendered}")
        lines.append(f"{level}]")
        return "\n".join(lines)
    raise TypeError(f"Unsupported SNBT value: {type(value).__name__}")


class FTBQuestWriter:
    """Write a Project into an FTB Quests v13 directory tree."""

    def write(self, project: Project, root: str | Path) -> Path:
        root_path = Path(root)
        quests_root = root_path / "quests" if root_path.name != "quests" else root_path
        chapters_dir = quests_root / "chapters"
        lang_dir = quests_root / "lang"
        chapters_dir.mkdir(parents=True, exist_ok=True)
        lang_dir.mkdir(parents=True, exist_ok=True)

        self._write_snbt(quests_root / "data.snbt", self._data(project))
        self._write_snbt(quests_root / "chapter_groups.snbt", {"chapter_groups": []})
        self._write_snbt(quests_root / "rewards.snbt", {})
        self._write_snbt(quests_root / "loot_crates.snbt", {})

        for chapter in project.chapters:
            self._write_snbt(chapters_dir / f"{chapter.id}.snbt", self._chapter(chapter))

        language = self._language(project)
        self._write_snbt(lang_dir / "en_us.snbt", language)
        return quests_root

    @staticmethod
    def _write_snbt(path: Path, value: Any) -> None:
        path.write_text(dumps(value) + "\n", encoding="utf-8")

    @staticmethod
    def _data(project: Project) -> dict[str, Any]:
        try:
            version: int | str = int(project.version)
        except ValueError:
            version = project.version
        return {
            "version": version,
            "default_hide_dependency_lines": False,
            "default_quest_shape": "",
            "disable_gui": False,
            "drop_loot_crates": False,
            "fallback_locale": "en_us",
        }

    def _chapter(self, chapter: Chapter) -> dict[str, Any]:
        raw = deepcopy(chapter.raw_data)
        raw["filename"] = chapter.id
        raw["id"] = self._ftb_id(chapter.ftb_id, chapter.uuid.int)
        raw["icon"] = chapter.icon
        raw["group"] = chapter.group or ""
        raw["quests"] = [self._quest(quest) for quest in chapter.quests]
        if chapter.background is not None:
            raw["background"] = chapter.background
        if chapter.color is not None:
            raw["color"] = chapter.color
        return raw

    def _quest(self, quest: Quest) -> dict[str, Any]:
        raw = deepcopy(quest.raw_data)
        raw["id"] = self._ftb_id(quest.ftb_id, quest.uuid.int)
        raw["x"] = float(quest.position.x)
        raw["y"] = float(quest.position.y)
        raw["icon"] = quest.icon
        raw["tasks"] = [self._task(task) for task in quest.tasks]

        if quest.rewards:
            raw["rewards"] = [self._reward(reward) for reward in quest.rewards]
        else:
            raw.pop("rewards", None)

        if quest.dependencies:
            raw["dependencies"] = [dependency.quest_id for dependency in quest.dependencies]
        else:
            raw.pop("dependencies", None)

        self._set_optional(raw, "hide", quest.hidden)
        self._set_optional(raw, "repeatable", quest.repeatable)
        self._set_optional(raw, "optional", quest.optional)
        return raw

    @staticmethod
    def _task(task: Task) -> dict[str, Any]:
        raw = deepcopy(task.raw_data)
        raw.update(task.data)
        raw["id"] = task.id
        raw["type"] = task.type.value
        return raw

    @staticmethod
    def _reward(reward: Reward) -> dict[str, Any]:
        raw = deepcopy(reward.raw_data)
        raw.update(reward.data)
        raw["id"] = reward.id
        raw["type"] = reward.type.value
        return raw

    @staticmethod
    def _language(project: Project) -> dict[str, str]:
        language = dict(project.language)
        for chapter in project.chapters:
            chapter_id = FTBQuestWriter._ftb_id(chapter.ftb_id, chapter.uuid.int)
            language[f"chapter.{chapter_id}.title"] = chapter.title
            if chapter.description:
                language[f"chapter.{chapter_id}.subtitle"] = chapter.description
            for quest in chapter.quests:
                quest_id = FTBQuestWriter._ftb_id(quest.ftb_id, quest.uuid.int)
                language[f"quest.{quest_id}.title"] = quest.title
                if quest.description:
                    language[f"quest.{quest_id}.subtitle"] = quest.description
        return language

    @staticmethod
    def _set_optional(raw: dict[str, Any], key: str, value: bool) -> None:
        if value:
            raw[key] = True
        else:
            raw.pop(key, None)

    @staticmethod
    def _ftb_id(existing: str | None, uuid_int: int) -> str:
        if existing:
            return existing.upper()
        return f"{uuid_int & ((1 << 64) - 1):016X}"
