from pathlib import Path
import hashlib, json, shutil, zipfile

ROOT=Path('/mnt/data/ImmersiveAdventureNeo-QuestBook')
if ROOT.exists(): shutil.rmtree(ROOT)
Q=ROOT/'config/ftbquests/quests'
(Q/'chapters').mkdir(parents=True)
(Q/'lang').mkdir(parents=True)
(ROOT/'tools').mkdir(parents=True)
(ROOT/'source').mkdir(parents=True)
(ROOT/'docs').mkdir(parents=True)

def hid(key):
    return hashlib.sha256(('ImmersiveAdventureNeo:'+key).encode()).hexdigest()[:16].upper()

chapter_id=hid('chapter:welcome')
quests=[
 dict(code='W01', title='Welcome to Immersive Adventure Neo', type='checkmark', x=0, y=0),
 dict(code='W02', title='Read the Journey Guide', type='checkmark', x=2, y=0, deps=['W01'], reward=('minecraft:bread',16)),
 dict(code='W03', title='Your First Log', type='item', item='minecraft:oak_log', count=1, x=4, y=0, deps=['W02'], reward=('minecraft:torch',16)),
 dict(code='W04', title='A Place to Work', type='item', item='minecraft:crafting_table', count=1, x=6, y=0, deps=['W03'], reward=('minecraft:stick',16)),
 dict(code='W05', title='The Stone Age', type='advancement', advancement='minecraft:story/mine_stone', x=8, y=0, deps=['W04'], reward=('minecraft:coal',8)),
 dict(code='W06', title='Acquire Hardware', type='advancement', advancement='minecraft:story/smelt_iron', x=10, y=0, deps=['W05'], reward=('minecraft:iron_ingot',4)),
 dict(code='W07', title='Sweet Dreams', type='advancement', advancement='minecraft:adventure/sleep_in_bed', x=12, y=0, deps=['W06'], reward=('minecraft:cooked_beef',8)),
 dict(code='W08', title='Ready for Adventure', type='checkmark', x=14, y=0, deps=['W07'], reward=('minecraft:torch',32)),
]
ids={q['code']:hid('quest:'+q['code']) for q in quests}

def task_block(q):
    tid=hid('task:'+q['code'])
    common='''\n\t\t\t\tReskillable: {\n\t\t\t\t\tcheck: 0b\n\t\t\t\t\tcomparison: "GREATER_OR_EQUAL"\n\t\t\t\t\tfirst: 10\n\t\t\t\t\tmode: "SKILL_LEVEL"\n\t\t\t\t\tsecond: 20\n\t\t\t\t\tskill_id: "mining"\n\t\t\t\t}\n\t\t\t\tSkillsLevel: {\n\t\t\t\t\tcategory: ""\n\t\t\t\t\tcheck: 0b\n\t\t\t\t\tcomparison: "GREATER_OR_EQUAL"\n\t\t\t\t\tfirst: 10\n\t\t\t\t\tmode: "TOTAL_LEVEL"\n\t\t\t\t\tsecond: 20\n\t\t\t\t}\n'''
    if q['type']=='checkmark': extra=f'\t\t\t\tid: "{tid}"\n\t\t\t\ttype: "checkmark"\n'
    elif q['type']=='item': extra=f'\t\t\t\tid: "{tid}"\n\t\t\t\titem: {{ count: {q.get("count",1)}, id: "{q["item"]}" }}\n\t\t\t\ttype: "item"\n'
    elif q['type']=='advancement': extra=f'\t\t\t\tadvancement: "{q["advancement"]}"\n\t\t\t\tcriterion: ""\n\t\t\t\tid: "{tid}"\n\t\t\t\ttype: "advancement"\n'
    return '\t\t\ttasks: [{' + common + extra + '\t\t\t}]\n'

def reward_block(q):
    if not q.get('reward'): return ''
    item,count=q['reward']; rid=hid('reward:'+q['code'])
    return f'''\t\t\trewards: [{{\n\t\t\t\tcount: {count}\n\t\t\t\tid: "{rid}"\n\t\t\t\titem: {{\n\t\t\t\t\tcount: 1\n\t\t\t\t\tid: "{item}"\n\t\t\t\t}}\n\t\t\t\ttype: "item"\n\t\t\t}}]\n'''

parts=['{\n\tdefault_hide_dependency_lines: false\n\tdefault_quest_shape: ""\n\tfilename: "00_welcome"\n\tgroup: ""\n',f'\tid: "{chapter_id}"\n\torder_index: 0\n\tquest_links: [ ]\n\tquests: [\n']
for i,q in enumerate(quests):
    parts.append('\t\t{\n')
    if q.get('deps'):
        deps=', '.join(f'"{ids[d]}"' for d in q['deps'])
        parts.append(f'\t\t\tdependencies: [{deps}]\n')
    parts.append(f'\t\t\tid: "{ids[q["code"]]}"\n')
    parts.append(reward_block(q))
    parts.append(task_block(q))
    parts.append(f'\t\t\tx: {float(q["x"]):.1f}d\n\t\t\ty: {float(q["y"]):.1f}d\n')
    parts.append('\t\t}' + ('' if i==len(quests)-1 else '') + '\n')
parts.append('\t]\n}\n')
(Q/'chapters/00_welcome.snbt').write_text(''.join(parts),encoding='utf-8')

# Exact baseline settings from uploaded v13 scaffold
(Q/'data.snbt').write_text('''{\n\tdefault_autoclaim_rewards: "disabled"\n\tdefault_consume_items: false\n\tdefault_quest_disable_jei: false\n\tdefault_quest_shape: "circle"\n\tdefault_reward_team: false\n\tdetection_delay: 20\n\tdisable_gui: false\n\tdrop_book_on_death: false\n\tdrop_loot_crates: false\n\temergency_items_cooldown: 300\n\tfallback_locale: "en_us"\n\tgrid_scale: 0.5d\n\thide_excluded_quests: false\n\tlock_message: ""\n\tloot_crate_no_drop: {\n\t\tboss: 0\n\t\tmonster: 600\n\t\tpassive: 4000\n\t}\n\tpause_game: false\n\tprogression_mode: "linear"\n\tshow_lock_icons: false\n\tverify_on_load: false\n\tversion: 13\n}\n''')
(Q/'chapter_groups.snbt').write_text('{\n\tchapter_groups: [ ]\n}\n')
# Keep these empty until schema is generated by editor; quest rewards are embedded safely.
(Q/'rewards.snbt').write_text('{\n}\n')
(Q/'loot_crates.snbt').write_text('{\n}\n')

lang=['{',f'\tchapter.{chapter_id}.title: "Immersive Adventure Neo"']
for q in quests:
    lang.append(f'\tquest.{ids[q["code"]]}.title: "{q["title"]}"')
lang.append('}')
(Q/'lang/en_us.snbt').write_text('\n'.join(lang)+'\n')

source={'project':'Immersive Adventure Neo','format_version':13,'chapter':{'code':'WELCOME','id':chapter_id,'filename':'00_welcome'},'quests':quests,'generated_ids':ids}
(ROOT/'source/welcome.json').write_text(json.dumps(source,indent=2),encoding='utf-8')

# Save reusable generator (this script itself)
shutil.copy('/mnt/data/build_ian.py', ROOT/'tools/generate.py')

(ROOT/'README.md').write_text(f'''# Immersive Adventure Neo — Quest Book\n\nRepository-ready FTB Quests project for Minecraft 1.21.1 NeoForge.\n\n## Compatibility\n\n- FTB Quests: 2101.1.27\n- Quest data format: v13\n- KubeJS: 2101.7.2-build.368\n\n## Install\n\nCopy `config/ftbquests/quests/` into the matching modpack instance folder. Back up the existing quest folder first.\n\nIn game, run `/ftbquests reload` as an operator, or restart the instance.\n\n## Included in v0.1.0\n\n- Eight-quest Welcome progression\n- Item, advancement, and checkmark tasks\n- Embedded item rewards\n- Linear dependencies\n- English localization\n- Deterministic IDs and generator source\n\n## Development\n\nEdit `source/welcome.json` as the human-readable reference. `tools/generate.py` currently contains the deterministic generator used for this release.\n\n## Important\n\n`rewards.snbt` and `loot_crates.snbt` are intentionally empty placeholders. Rewards in this release are embedded directly in quests, matching the verified scaffold.\n''')
(ROOT/'CHANGELOG.md').write_text('''# Changelog\n\n## 0.1.0 - 2026-07-16\n\n- Added the repository structure.\n- Added the Immersive Adventure Neo Welcome chapter.\n- Added eight linked quests and starter rewards.\n- Added deterministic quest ID generation.\n- Added FTB Quests v13 baseline configuration and localization.\n''')
(ROOT/'docs/TESTING.md').write_text('''# In-game testing\n\n1. Back up the existing `config/ftbquests/quests` folder.\n2. Copy this repository's `config/ftbquests/quests` folder into the instance.\n3. Start a temporary world with editing mode disabled.\n4. Run `/ftbquests reload` or restart.\n5. Confirm the Welcome chapter opens and all eight quests appear in a line.\n6. Complete Oak Log, Crafting Table, Stone Age, Acquire Hardware, and Sweet Dreams naturally.\n7. Confirm each reward can be claimed and each dependency unlocks correctly.\n8. If parsing fails, preserve `latest.log` and the generated quest folder for diagnosis.\n''')
(ROOT/'.gitignore').write_text('''# OS/editor\n.DS_Store\nThumbs.db\n.vscode/\n.idea/\n\n# Python\n__pycache__/\n*.pyc\n\n# Local test output\nrun/\nlogs/\ncrash-reports/\n''')

zip_path=Path('/mnt/data/ImmersiveAdventureNeo-QuestBook-v0.1.0.zip')
if zip_path.exists(): zip_path.unlink()
with zipfile.ZipFile(zip_path,'w',zipfile.ZIP_DEFLATED) as z:
    for p in ROOT.rglob('*'):
        if p.is_file(): z.write(p,p.relative_to(ROOT.parent))
print(zip_path)
print('files',sum(1 for p in ROOT.rglob('*') if p.is_file()))
